name: testlib_internal_tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  testlib_internal_tests_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build the internal tests
        run: make build_test_internal

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            out/*.test_internal
            out/*.so
          if-no-files-found: error  # Fail if no files are found

  testlib_internal_tests_run:
    # This ensures that the test job runs only if the build job succeeds
    needs: testlib_internal_tests_build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: build

      - name: Configure Linker Library Path
        run: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${{ github.workspace }}/build

      - name: Make artifacts executable
        run: chmod +x build/*.test_internal

      - name: Run tests
        run: make test_internal
